name: "Deploy"
on:
  pull_request:
      branches: [ master ]
  push:
      branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/6405edf2dca7f6faaa29266136dfa7f8f969b511.tar.gz
    - run: cd mine-site && nix-build && ./result/bin/site build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mine-site/_site
